# Generated by Django 2.2.3 on 2019-07-16 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenapi', '0002_auto_20190716_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='soilmoisturereadingmodel',
            name='value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tanklevelreadingmodel',
            name='sensorReading',
            field=models.FloatField(default=0),
        ),
    ]
