# Generated by Django 2.2.3 on 2019-07-16 20:10

from django.db import migrations

def init_plants(apps, schema_editor):
  plants = {
    '2': 'beefeater',
    '3': 'roma1',
    '4': 'roma2',
    '5': 'cherry'
  }

  PlantModel = apps.get_model('gardenapi', 'PlantModel')

  for k, v in plants.items():
    PlantModel.objects.create(id=int(k), description=v)

class Migration(migrations.Migration):

    dependencies = [
        ('gardenapi', '0003_auto_20190716_0231'),
    ]

    operations = [
      migrations.RunPython(init_plants),
    ]
